### ISSUE TITLE
Published 1.0.0 doesn't have `lib` directory

### ISSUE THREAD

**Issue by brettdh** [zinserjan/shim-loader#6]
```
/tmp/testloader$ npm i shim-loader@0.1.0                                                                                                                                               
<snip>
/tmp/testloader$ ls node_modules/shim-loader                                                                                                                                           
LICENSE.md   README.md    lib          package.json src
/tmp/testloader$ node
> require('shim-loader')
[Function: shimLoader]

/tmp/testloader$ rm -rf node_modules                                                                                                                                                   
/tmp/testloader$ npm i shim-loader@1.0.0                                                                                                                                               
<snip>
/tmp/testloader$ ls node_modules/shim-loader                                                                                                                                           
LICENSE.md   README.md    package.json src
/tmp/testloader$ node
> require('shim-loader')
Error: Cannot find module 'shim-loader'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
```
You may want to use `prepublish` and `prepublishOnly` scripts to avoid this in the future:
https://resin.io/blog/safely-migrating-away-from-prepublish-with-npm-4/

**Comment by zinserjan** [comment]
Oh my god, seems that I published the initial version manually :unamused:
I thought that I did this with np as in my other projects. Thanks for reporting this. I'll publish a new release.

**Comment by zinserjan** [comment]
Published 1.0.1 with lib files :laughing:

**Comment by brettdh** [comment]
Thanks for fixing so fast! 😮 

Out of curiosity, do you know why Travis didn't catch this issue? It seems to have run with 1.0.0...

**Comment by zinserjan** [comment]
With Travis you mean the Travis CI in this project? It didn't catch this issue cause it uses babel-register (see [here](https://github.com/zinserjan/shim-loader/blob/v1.0.1/package.json#L15) and [here](https://github.com/zinserjan/shim-loader/blob/v1.0.1/test/test.js#L7))

**Comment by brettdh** [comment]
Ah, gotcha. Makes sense. And lol, yes, I meant Travis CI, not some dude named Travis. :)
